Repository 9oormthon-univ/goormthon_univ, pull requests merged in 2023-12, with the labels that each got.

#1 feat: 네브바, 푸터 제작
  src/@components/layout/Layout.jsx
  src/@components/layout/footer/Footer.jsx
  src/@components/layout/footer/style.jsx
  src/@components/layout/navbar/Navbar.jsx
  src/@components/layout/navbar/style.jsx
  src/@pages/Recruit.jsx
  src/@pages/recruit/Recruit.jsx
  src/@pages/recruit/style.jsx
  src/Router.jsx
  src/assets/images/university/chungang.png
  src/assets/images/university/dongduk.png
  src/assets/images/university/dongguk.png
  src/assets/images/university/duckseong.png
  src/assets/images/university/incheon.png
  src/assets/images/university/kangwoon.png
  src/assets/images/university/koomin.png
  src/assets/images/university/koreaSaejong.png
  src/assets/images/university/sangmyeong.png
  src/assets/images/university/sungkonghoe.png
Labels: feature ✨, refactor 🔨, setting ⚙️, size/L, 🙋‍♂️ 희찬

#2 Feat : 모집페이지 완료
  package-lock.json
  package.json
  public/favicon.ico
  public/favicon/android-icon-144x144.png
  public/favicon/android-icon-192x192.png
  public/favicon/android-icon-36x36.png
  public/favicon/android-icon-48x48.png
  public/favicon/android-icon-72x72.png
  public/favicon/android-icon-96x96.png
  public/favicon/apple-icon-114x114.png
  public/favicon/apple-icon-120x120.png
  public/favicon/apple-icon-144x144.png
  public/favicon/apple-icon-152x152.png
  public/favicon/apple-icon-180x180.png
  public/favicon/apple-icon-57x57.png
  public/favicon/apple-icon-60x60.png
  public/favicon/apple-icon-72x72.png
  public/favicon/apple-icon-76x76.png
  public/favicon/apple-icon-precomposed.png
  public/favicon/apple-icon.png
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon-96x96.png
  public/favicon/favicon.ico
  public/favicon/ms-icon-144x144.png
  public/favicon/ms-icon-150x150.png
  public/favicon/ms-icon-310x310.png
  public/favicon/ms-icon-70x70.png
  public/index.css
  public/index.html
  public/manifest.json
  src/@components/layout/navbar/Navbar.jsx
  src/@components/layout/navbar/style.jsx
  src/@components/recruit/UniversityItem/UniversityItem.jsx
  src/@components/recruit/UniversityItem/style.jsx
  src/@components/recruit/recruitCaution/RecruitCaution.jsx
  src/@components/recruit/recruitFAQ/RecruitFAQ.jsx
  src/@components/recruit/recruitFAQ/style.jsx
  src/@components/recruit/recuritCautionRowBox/RecuritCautionRowBox.jsx
  src/@components/recruit/recuritCautionRowBox/style.jsx
  src/@components/recruit/recuritHeader/RecuritHeader.jsx
  src/@components/recruit/recuritHeader/style.css
  src/@components/recruit/recuritHeader/style.jsx
  src/@components/recruit/recuritTarget/RecuritTarget.jsx
  src/@components/recruit/recuritTarget/style.jsx
  src/@pages/apply/Apply.jsx
  src/@pages/apply/style.jsx
  src/@pages/errors/NotFound.jsx
  src/@pages/errors/style.jsx
  src/@pages/recruit/Recruit.jsx
  src/@pages/recruit/style.jsx
  src/Router.jsx
  src/assets/images/dummy.png
  src/assets/images/notfound.png
  src/assets/images/university/koreaSaejong.png
  src/assets/images/university/sangmyeong.png
  src/utilities/FAQData.js
  src/utilities/UnivData.js
Labels: feature ✨, refactor 🔨, size/XXL, style 🎨, 🙋‍♂️ 희찬

#3 Feat : About 페이지 메인 배너
  goorm.manifest
  public/index.html
  src/@components/about/.keep
  src/@components/about/MainBanner/MainBanner.jsx
  src/@components/about/MainBanner/style.jsx
  src/@components/about/SlidingText/SlidingText.jsx
  src/@components/about/SlidingText/TextContent.jsx
  src/@components/about/SlidingText/style.jsx
  src/@pages/about/About.jsx
  src/assets/svgs/GoormieeEffect.jsx
  src/assets/svgs/ampersand.svg
  src/assets/svgs/arrow-right.svg
  src/assets/svgs/beotkkot.svg
  src/assets/svgs/danpoong.svg
  src/assets/svgs/goormiee.svg
  src/assets/svgs/goormiee_effect.svg
Labels: feature ✨, size/L, style 🎨, 🙋‍♀️ 은서

#5 feat: project
  src/@pages/Project.jsx
  src/@pages/project/Project.jsx
  src/@pages/project/style.jsx
  src/Router.jsx
  src/assets/images/dummyBanner.png
  src/assets/images/projectDummy.png
Labels: feature ✨, size/L, 🙋‍♂️ 희찬

#7 fix: getBoundingClientRect null 참조 에러 해결, 구르미 위 click 글씨 고정
  src/@components/about/MainBanner/MainBanner.jsx
  src/@components/about/MainBanner/style.jsx
  src/@components/about/Plan/Timeline.jsx
  src/assets/svgs/GoormieeEffect.jsx
Labels: bugfix 🐞, size/M, style 🎨, 🙋‍♀️ 은서

#9 feat: About 페이지 goal 섹션
  src/@components/about/Intro/Intro.jsx
  src/@components/about/Plan/Card.jsx
  src/@components/about/Plan/Timeline.jsx
  src/@components/about/Plan/style.jsx
  src/@components/about/goal/Intro.jsx
  src/@components/about/goal/style.jsx
  src/@pages/about/About.jsx
  src/assets/svgs/goal-graphic.svg
  src/assets/svgs/goal-rain.svg
Labels: size/L, style 🎨, 🙋‍♀️ 은서

#11 feat: 각종 모바일 반응형 개선 작업
  src/@components/layout/footer/style.jsx
  src/@components/layout/navbar/Navbar.jsx
  src/@components/layout/navbar/style.jsx
  src/@components/project/ProjectCard.jsx
  src/@components/recruit/recruitCaution/RecruitCaution.jsx
  src/@components/recruit/recruitFAQ/RecruitFAQ.jsx
  src/@components/recruit/recuritTarget/RecuritTarget.jsx
  src/@pages/project/Project.jsx
  src/@pages/project/style.jsx
  src/assets/images/projects/team7.png
  src/assets/images/season.png
Labels: refactor 🔨, size/L, 🙋‍♂️ 희찬

#12 Feat: About 페이지 activity 섹션
  src/@components/about/activity/Activity.jsx
  src/@components/about/activity/ActivityItem.jsx
  src/@components/about/activity/ActivityList.jsx
  src/@components/about/activity/style.jsx
  src/@components/about/benefit/Benefit.jsx
  src/@components/about/goal/goal.jsx
  src/@components/about/goal/style.jsx
  src/@components/about/intro/Intro.jsx
  src/@components/about/intro/style.jsx
  src/@components/about/plan/Plan.jsx
  src/@components/about/plan/style.jsx
  src/@components/layout/GridContainer.jsx
  src/@pages/about/About.jsx
  src/assets/images/about/activity1.png
  src/assets/images/about/activity2.png
  src/assets/images/about/activity3.png
  src/assets/images/about/activity4.png
Labels: size/L

#14 fix: About 페이지 각종 디테일
  src/@components/about/activity/ActivityList.jsx
  src/@components/about/activity/style.jsx
  src/@components/about/benefit/BenefitList.jsx
  src/@components/about/intro/style.jsx
  src/@components/about/plan/Timeline.jsx
  src/@components/layout/footer/style.jsx
  src/utilities/AboutData.js
Labels: size/L

#15 Feature/apply
  .env
  goorm.manifest
  package-lock.json
  package.json
  src/@components/about/activity/style.jsx
  src/@components/about/intro/Intro.jsx
  src/@components/about/intro/style.jsx
  src/@components/layout/navbar/Navbar.jsx
  src/@components/project/ProjectCard.jsx
  src/@components/recruit/recruitCalendar/RecuritCalendar.jsx
  src/@components/recruit/recruitCalendar/style.jsx
  src/@components/recruit/recruitCaution/RecruitCaution.jsx
  src/@components/recruit/recuritHeader/RecuritHeader.jsx
  src/@components/recruit/recuritTarget/RecuritTarget.jsx
  src/@pages/apply/Apply.jsx
  src/@pages/errors/NotFound.jsx
  src/@pages/project/Project.jsx
  src/@pages/project/style.jsx
  src/@pages/recruit/Recruit.jsx
  src/@pages/recruit/style.jsx
  src/Router.jsx
  src/assets/images/calendar.png
  src/fbase.js
  src/utilities/FAQData.js
  src/utilities/ProjectData.js
Labels: feature ✨, size/L, 🙋‍♂️ 희찬

#16 feat: About 페이지 반응형 작업 일부 완료
  src/@components/about/activity/style.jsx
  src/@components/about/benefit/Benefit.jsx
  src/@components/about/goal/goal.jsx
  src/@components/about/goal/style.jsx
  src/@components/about/intro/Intro.jsx
  src/@components/about/plan/planDesktop/Card.jsx
  src/@components/about/plan/planDesktop/PlanDesktop.jsx
  src/@components/about/plan/planDesktop/Timeline.jsx
  src/@components/about/plan/planDesktop/style.jsx
  src/@components/about/plan/planMobile/Card.jsx
  src/@components/about/plan/planMobile/PlanMobile.jsx
  src/@components/about/plan/planMobile/Timeline.jsx
  src/@components/about/plan/planMobile/style.jsx
  src/@components/layout/GridContainer.jsx
  src/@components/layout/Layout.jsx
  src/@components/layout/footer/CustomFooter.jsx
  src/@pages/about/About.jsx
  src/@pages/about/style.jsx
  src/utilities/AboutData.js
Labels: size/L

#18 feat: 혜택 부분 스크롤에 따른 인터랙션 구현
  goorm.manifest
  package-lock.json
  package.json
  src/@components/about/benefit/Benefit.jsx
  src/@components/about/benefit/BenefitItem.jsx
  src/@components/about/benefit/BenefitList.jsx
  src/@components/about/benefit/HorizontalScroll.jsx
  src/@components/about/benefit/style.jsx
  src/utilities/AboutData.js
Labels: size/L

#19 feat: about mainBanner 섹션 반응형 완료
  src/@components/about/mainBanner/MainBanner.jsx
  src/@components/about/mainBanner/style.jsx
  src/@components/layout/navbar/Navbar.jsx
  src/@components/layout/navbar/style.jsx
  src/assets/svgs/GoormieeEffectSmall.jsx
Labels: size/M

#20 feat: about intro 섹션 반응형 완료 (테블릿 뷰 제외)
  src/@components/about/intro/style.jsx
  src/@components/layout/navbar/Navbar.jsx
Labels: size/S
