Repository 9oormthon-univ/goormthon_univ, pull requests merged in 2024-01, with the labels that each got.

#24 design: About 페이지 메인 배너 구르미와 텍스트 위치 조정
  src/@components/about/mainBanner/MainBanner.jsx
  src/@components/about/mainBanner/style.jsx
  src/assets/svgs/GoormieeEffect.jsx
  src/assets/svgs/GoormieeEffectSmall.jsx
  src/assets/svgs/MainBannerImg.jsx
  src/assets/svgs/MainBannerSmallImg.jsx
  src/assets/svgs/goormiee_effect.svg
  src/assets/svgs/goormiee_small.svg
Labels: size/L, design 🎨, 🙋‍♀️ 은서

#38 Refactor : 컬러코드, 컴포넌트 적용
  goorm.manifest
  src/@components/about/activity/style.jsx
  src/@components/about/benefit/BenefitDesktop/style.jsx
  src/@components/about/benefit/BenefitMobile/style.jsx
  src/@components/about/findingUniv/FindingUniv.jsx
  src/@components/about/findingUniv/style.jsx
  src/@components/about/goal/style.jsx
  src/@components/about/intro/style.jsx
  src/@components/about/mainBanner/style.jsx
  src/@components/about/plan/planDesktop/PlanDesktop.jsx
  src/@components/about/plan/planDesktop/style.jsx
  src/@components/about/plan/planMobile/style.jsx
  src/@components/about/slidingText/style.jsx
  src/@components/layout/footer/style.jsx
  src/@components/layout/navbar/Navbar.jsx
  src/@components/layout/navbar/style.jsx
  src/@components/recruit/recruitCalendar/style.jsx
  src/@components/recruit/recruitCaution/RecruitCaution.jsx
  src/@components/recruit/recruitFAQ/style.jsx
  src/@components/recruit/recuritCautionRowBox/style.jsx
  src/@components/recruit/recuritHeader/RecuritHeader.jsx
  src/@components/recruit/recuritHeader/style.jsx
  src/@components/recruit/recuritTarget/RecuritTarget.jsx
  src/@components/recruit/recuritTarget/style.jsx
  src/@pages/apply/Apply.jsx
  src/@pages/apply/style.jsx
  src/@pages/project/style.jsx
  src/@pages/recruit/style.jsx
  src/fbase.js
Labels: refactor 🔨, size/L, design 🎨, 🙋‍♂️ 희찬

#41 Refactor/recruit
  public/index.html
  src/@components/layout/footer/CustomFooter.jsx
  src/@components/layout/footer/style.jsx
  src/@components/layout/navbar/style.jsx
  src/@components/recruit/recruitUnivScrolling/RecruitUnivScrolling.jsx
  src/@components/recruit/recuritHeader/RecuritHeader.jsx
  src/assets/images/about/aa.png
  src/assets/images/about/activity4.png
Labels: feature ✨, refactor 🔨, size/L, 🙋‍♂️ 희찬

#43 [Design] About 페이지 mainBanner 디자인 변경
  goorm.manifest
  public/index.css
  src/@components/about/benefit/BenefitDesktop/style.jsx
  src/@components/about/benefit/BenefitMobile/style.jsx
  src/@components/about/goal/style.jsx
  src/@components/about/intro/Intro.jsx
  src/@components/about/intro/style.jsx
  src/@components/about/mainBanner/MainBanner.jsx
  src/@components/about/mainBanner/style.jsx
  src/@components/about/plan/planDesktop/style.jsx
  src/@components/about/slidingText/style.jsx
  src/@components/layout/GridContainer.jsx
  src/@components/layout/footer/style.jsx
  src/@components/layout/navbar/Navbar.jsx
  src/@components/layout/navbar/style.jsx
  src/assets/svgs/MainBannerImg.jsx
  src/assets/svgs/MainBannerSmallImg.jsx
  src/assets/svgs/main-cloud-up.svg
  src/assets/svgs/main_banner_slogan.svg
Labels: size/L, design 🎨, 🙋‍♀️ 은서

#49 [Design] About 페이지 plan 섹션 디자인 수정
  src/@components/about/mainBanner/style.jsx
  src/@components/about/plan/planDesktop/CardListLower.jsx
  src/@components/about/plan/planDesktop/CardListUpper.jsx
  src/@components/about/plan/planDesktop/PlanDesktop.jsx
  src/@components/about/plan/planDesktop/Timeline.jsx
  src/@components/about/plan/planDesktop/style.jsx
  src/@components/about/plan/planMobile/PlanMobile.jsx
  src/@components/about/plan/planMobile/Timeline.jsx
  src/@components/about/plan/planMobile/style.jsx
  src/@components/layout/navbar/style.jsx
  src/@pages/about/style.jsx
  src/utilities/AboutData.js
Labels: feature ✨, size/L, design 🎨, 🙋‍♀️ 은서

#55 [Refactor] goormStrap 적용 - Recurit Screen
  src/@components/layout/Layout.jsx
  src/@components/recruit/recruitCalendar/RecuritCalendar.jsx
  src/@components/recruit/recruitCalendar/style.jsx
  src/@components/recruit/recruitFAQ/RecruitFAQ.jsx
  src/@components/recruit/recruitFAQ/style.jsx
  src/@components/recruit/recuritHeader/RecuritHeader.jsx
  src/@components/recruit/recuritTarget/RecuritTarget.jsx
  src/@components/recruit/recuritTarget/style.jsx
  src/@pages/recruit/Recruit.jsx
  src/@pages/recruit/style.jsx
Labels: refactor 🔨, size/L, 🙋‍♂️ 희찬

#57 [Design] About 페이지 activity 섹션 반응형 추가
  src/@components/about/activity/Activity.jsx
  src/@components/about/activity/ActivityList.jsx
  src/@components/about/activity/style.jsx
  src/assets/images/about/activity3.png
  src/assets/images/about/activity4.png
  src/assets/images/about/activity5.png
  src/utilities/AboutData.js
Labels: size/L, design 🎨, 🙋‍♀️ 은서

#59 [Design] 반응형 디테일 수정
  src/@components/about/benefit/BenefitDesktop/BenefitDesktop.jsx
  src/@components/about/benefit/BenefitDesktop/style.jsx
  src/@components/about/findingUniv/FindingUniv.jsx
  src/@components/about/findingUniv/style.jsx
  src/@components/about/goal/style.jsx
  src/@components/about/intro/Intro.jsx
  src/@components/about/intro/style.jsx
Labels: size/L, design 🎨, 🙋‍♀️ 은서

#63 [Style] About 페이지 goormstrap + scss 적용
  goorm.manifest
  package-lock.json
  package.json
  src/@components/about/activity/Activity.jsx
  src/@components/about/activity/Activity.module.scss
  src/@components/about/activity/ActivityItem.jsx
  src/@components/about/activity/ActivityList.jsx
  src/@components/about/activity/style.jsx
  src/@components/about/benefit/BenefitDesktop/BenefitDesktop.jsx
  src/@components/about/benefit/BenefitDesktop/BenefitDesktop.module.scss
  src/@components/about/benefit/BenefitDesktop/BenefitItem.jsx
  src/@components/about/benefit/BenefitDesktop/HorizontalScroll.jsx
  src/@components/about/benefit/BenefitDesktop/style.jsx
  src/@components/about/benefit/BenefitMobile/BenefitItem.jsx
  src/@components/about/benefit/BenefitMobile/BenefitList.jsx
  src/@components/about/benefit/BenefitMobile/BenefitMobile.jsx
  src/@components/about/benefit/BenefitMobile/BenefitMobile.module.scss
  src/@components/about/benefit/BenefitMobile/style.jsx
  src/@components/about/goal/Goal.jsx
  src/@components/about/goal/Goal.module.scss
  src/@components/about/goal/goal.jsx
  src/@components/about/goal/style.jsx
  src/@components/about/intro/Intro.jsx
  src/@components/about/intro/Intro.module.scss
  src/@components/about/intro/style.jsx
  src/@components/about/mainBanner/MainBanner.jsx
  src/@components/about/mainBanner/MainBanner.module.scss
  src/@components/about/mainBanner/style.jsx
  src/@components/about/plan/planDesktop/Card.jsx
  src/@components/about/plan/planDesktop/CardListLower.jsx
  src/@components/about/plan/planDesktop/CardListUpper.jsx
  src/@components/about/plan/planDesktop/PlanDesktop.jsx
  src/@components/about/plan/planDesktop/PlanDesktop.module.scss
  src/@components/about/plan/planDesktop/Timeline.jsx
  src/@components/about/plan/planDesktop/style.jsx
  src/@components/about/plan/planMobile/Card.jsx
  src/@components/about/plan/planMobile/CardList.jsx
  src/@components/about/plan/planMobile/PlanMobile.jsx
  src/@components/about/plan/planMobile/PlanMobile.module.scss
  src/@components/about/plan/planMobile/Timeline.jsx
  src/@components/about/plan/planMobile/style.jsx
  src/@pages/about/About.jsx
  src/@pages/about/style.jsx
  src/assets/images/about/img-danpoong-hover.png
  src/assets/images/about/img-goorm-default.png
  src/assets/images/about/img-goorm-hover.png
  src/style/_breakpoints.scss
  src/style/globalStyle.js
  src/style/mixin.scss
  src/style/theme.js
  src/utilities/AboutData.js
Labels: size/XXL, design 🎨, 🙋‍♀️ 은서

#62 [feat] GoormNavBar 적용
  src/@components/layout/Layout.jsx
  src/@components/layout/navbar/CustomNavbar.jsx
  src/@components/layout/navbar/Navbar.jsx
  src/@components/layout/navbar/style.jsx
Labels: feature ✨, size/L, 🙋‍♀️ 은서

#65 [Fix] About 페이지 디테일 수정
  src/@components/about/activity/ActivityItem.jsx
  src/@components/about/benefit/BenefitDesktop/BenefitItem.jsx
  src/@components/about/benefit/BenefitMobile/BenefitItem.jsx
  src/@components/about/goal/Goal.jsx
  src/@components/about/intro/Intro.jsx
  src/@components/about/mainBanner/MainBanner.jsx
  src/@components/about/plan/planDesktop/Card.jsx
  src/@components/about/plan/planDesktop/CardListLower.jsx
  src/@components/about/plan/planDesktop/CardListUpper.jsx
  src/@components/about/plan/planDesktop/PlanDesktop.jsx
  src/@components/about/plan/planDesktop/PlanDesktop.module.scss
  src/@components/about/plan/planDesktop/Timeline.jsx
  src/@components/layout/navbar/CustomNavbar.jsx
  src/@pages/apply/Apply.jsx
  src/@pages/errors/NotFound.jsx
  src/Router.jsx
Labels: bugfix 🐞, size/L, 🙋‍♀️ 은서

#67 [Design] Project 페이지 모달 디자인 수정
  src/@components/project/.keep
  src/@components/project/ProjectCard.jsx
  src/@components/project/projectModal/ProjectModal.jsx
  src/@components/project/projectModal/style.js
  src/@components/project/projectModal/style.jsx
Labels: size/L, design 🎨, 🙋‍♀️ 은서

#68 Feature/remake recruit
  src/@components/ apply/ApplyHeader.jsx
  src/@components/ apply/style.jsx
  src/@components/recruit/UniversityItem/UniversityItem.jsx
  src/@components/recruit/UniversityItem/style.jsx
  src/@components/recruit/recruitFAQ/RecruitFAQ.jsx
  src/@components/recruit/recruitFAQ/style.jsx
  src/@components/recruit/recruitUnivScrolling/RecruitUnivScrolling.jsx
  src/@components/recruit/recuritHeader/RecuritHeader.jsx
  src/@components/recruit/recuritHeader/style.css
  src/@components/recruit/recuritHeader/style.jsx
  src/@pages/apply/Apply.jsx
  src/@pages/apply/style.jsx
  src/assets/images/calendar.png
  src/assets/images/university_row/chungang.png
  src/assets/images/university_row/dongduk.png
  src/assets/images/university_row/dongguk.png
  src/assets/images/university_row/ducksung.png
  src/assets/images/university_row/incheon.png
  src/assets/images/university_row/kangwoon.png
  src/assets/images/university_row/koomin.png
  src/assets/images/university_row/koreaSaejong.png
  src/assets/images/university_row/sangmyeong.png
  src/assets/images/university_row/sungkonghoe.png
  src/utilities/UnivData.js
Labels: refactor 🔨, size/L, design 🎨, 🙋‍♂️ 희찬

#69 Feature/remake recruit
  goorm.manifest
  src/@components/layout/Layout.jsx
  src/@components/project/projectModal/ProjectModal.jsx
  src/@components/project/projectModal/style.jsx
  src/@components/recruit/UniversityItem/style.jsx
  src/@components/recruit/recruitModal/RecruitModal.jsx
  src/@components/recruit/recruitModal/style.jsx
  src/@components/recruit/recruitUnivScrolling/RecruitUnivScrolling.jsx
  src/@components/recruit/recuritHeader/RecuritHeader.jsx
  src/@components/recruit/recuritHeader/style.jsx
  src/@components/recruit/recuritTarget/RecuritTarget.jsx
  src/@pages/recruit/Recruit.jsx
  src/@pages/recruit/style.jsx
  src/assets/images/calendar.png
  src/assets/images/univ/univ-HUFS.png
  src/assets/images/univ/univ-ajou.png
  src/assets/images/univ/univ-cau.png
  src/assets/images/univ/univ-chonnam.png
  src/assets/images/univ/univ-dankook.png
  src/assets/images/univ/univ-dongduk.png
  src/assets/images/univ/univ-dongguk.png
  src/assets/images/univ/univ-duksung.png
  src/assets/images/univ/univ-ewha.png
  src/assets/images/univ/univ-gachon.png
  src/assets/images/univ/univ-hallym.png
  src/assets/images/univ/univ-hansung.png
  src/assets/images/univ/univ-incheon.png
  src/assets/images/univ/univ-kookmin.png
  src/assets/images/univ/univ-korea.png
  src/assets/images/univ/univ-kwangwoon.png
  src/assets/images/univ/univ-kyonggi.png
  src/assets/images/univ/univ-kyunghee.png
  src/assets/images/univ/univ-sangmyung(cheonan).png
  src/assets/images/univ/univ-sangmyung(seoul).png
  src/assets/images/univ/univ-sch.png
  src/assets/images/univ/univ-sehan.png
  src/assets/images/univ/univ-sejong.png
  src/assets/images/univ/univ-sungkonghoe.png
  src/assets/images/univ/univ-swu.png
  src/assets/images/university/univ-cau.png
  src/assets/images/university/univ-dongduk.png
  src/assets/images/university/univ-dongguk.png
  src/assets/images/university/univ-duksung.png
  src/assets/images/university/univ-incheon.png
  src/assets/images/university/univ-kookmin.png
  src/assets/images/university/univ-korea.png
  src/assets/images/university/univ-kwangwoon.png
  src/assets/images/university/univ-sangmyung(cheonan).png
  src/assets/images/university/univ-sangmyung(seoul).png
  src/assets/images/university/univ-sungkonghoe.png
  src/utilities/UnivData.js
Labels: feature ✨, size/XL, 🙋‍♂️ 희찬
